"""create businesses tables

Revision ID: db18d4801ce3
Revises: 
Create Date: 2026-06-24 19:33:55.736850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db18d4801ce3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('default_salary_basis', sa.Enum('WORKING_26_DAYS', 'CALENDAR_DAYS', name='salary_basis_enum'), nullable=False),
    sa.Column('payroll_start_day', sa.Integer(), nullable=False),
    sa.Column('default_wage_type', sa.Enum('DAILY', 'MONTHLY', 'HOURLY', name='wage_type_enum'), nullable=False),
    sa.Column('default_working_hours_per_day', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('default_overtime_multiplier', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.CheckConstraint('default_overtime_multiplier >= 1', name='check_default_overtime_multiplier'),
    sa.CheckConstraint('default_working_hours_per_day > 0 AND default_working_hours_per_day <= 24', name='check_default_working_hours_per_day'),
    sa.CheckConstraint('payroll_start_day >= 1 AND payroll_start_day <= 28', name='check_payroll_start_day'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'slug', name='uq_business_owner_slug')
    )
    op.create_table('weekly_off_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday_enum'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'weekday', name='uq_weekly_off_rule_business_weekday')
    )
    op.create_index('ix_weekly_off_rule_business_id', 'weekly_off_rules', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weekly_off_rule_business_id', table_name='weekly_off_rules')
    op.drop_table('weekly_off_rules')
    op.drop_table('businesses')
    # ### end Alembic commands ###
