"""create business tables

Revision ID: d83358423006
Revises:
Create Date: 2026-06-19 20:00:11.942536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d83358423006"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "businesses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("normalized_name", sa.String(length=100), nullable=False),
        sa.Column(
            "default_wage_type",
            sa.Enum("HOURLY", "DAILY", "MONTHLY", name="wage_type", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "default_working_hours_per_day",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "default_overtime_multiplier",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "payroll_start_day", sa.Integer(), server_default="1", nullable=False
        ),
        sa.CheckConstraint(
            "payroll_start_day >= 1 AND payroll_start_day <= 28",
            name="ck_business_payroll_start_day",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_id", "normalized_name", name="uq_business_owner_normalized_name"
        ),
    )
    op.create_index(
        op.f("ix_businesses_owner_id"), "businesses", ["owner_id"], unique=False
    )
    op.create_table(
        "business_weekly_off_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column(
            "weekday",
            sa.Enum(
                "MONDAY",
                "TUESDAY",
                "WEDNESDAY",
                "THURSDAY",
                "FRIDAY",
                "SATURDAY",
                "SUNDAY",
                name="weekday",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("week_of_month", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "week_of_month IS NULL OR (week_of_month >= 1 AND week_of_month <= 5)",
            name="ck_weekly_off_rule_week_of_month",
        ),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_business_weekly_off_rules_business_id"),
        "business_weekly_off_rules",
        ["business_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_business_weekly_off_rules_business_id"),
        table_name="business_weekly_off_rules",
    )
    op.drop_table("business_weekly_off_rules")
    op.drop_index(op.f("ix_businesses_owner_id"), table_name="businesses")
    op.drop_table("businesses")
    # ### end Alembic commands ###
