"""create holidays table

Revision ID: ef20973af35e
Revises: db18d4801ce3
Create Date: 2026-06-26 17:00:00.368621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef20973af35e'
down_revision: Union[str, Sequence[str], None] = 'db18d4801ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('holiday_name', sa.String(length=255), nullable=True),
    sa.Column('is_paid', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'holiday_date', name='uq_holiday_business_date')
    )
    op.create_index(op.f('ix_holidays_business_id'), 'holidays', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holidays_business_id'), table_name='holidays')
    op.drop_table('holidays')
    # ### end Alembic commands ###
