"""create employees table

Revision ID: 2c1bc82dd3f8
Revises: ef20973af35e
Create Date: 2026-06-26 18:03:29.076779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c1bc82dd3f8'
down_revision: Union[str, Sequence[str], None] = 'ef20973af35e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('wage_type', sa.Enum('daily', 'monthly', 'hourly', name='wage_type', native_enum=False), nullable=False),
    sa.Column('salary_basis', sa.Enum('working_26_days', 'calendar_days', name='salary_basis', native_enum=False), nullable=False),
    sa.Column('wage_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('working_hours_per_day', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overtime_multiplier', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_business_id'), 'employees', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_business_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
