"""create attendances table

Revision ID: 7fda5131247d
Revises: 2c1bc82dd3f8
Create Date: 2026-06-27 16:32:43.594206

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM

# revision identifiers, used by Alembic.
revision: str = "7fda5131247d"
down_revision: Union[str, Sequence[str], None] = "2c1bc82dd3f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attendances",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            PG_ENUM(
                "PRESENT",
                "HALF_DAY",
                "ABSENT",
                "PAID_LEAVE",
                "UNPAID_LEAVE",
                "PAID_HOLIDAY",
                "UNPAID_HOLIDAY",
                name="attendance_status_enum",
                create_type=False,  # <- important
            ),
            nullable=False,
        ),
        sa.Column("total_hours", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("overtime_hours", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("marked_by", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "overtime_hours >= 0", name="check_overtime_hours_non_negative"
        ),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "business_id",
            "employee_id",
            "date",
            name="uq_attendance_business_employee_date",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attendances")
    # ### end Alembic commands ###
