"""add attendance table

Revision ID: f0412173ff62
Revises: 2c120e249b8c
Create Date: 2026-06-22 15:52:12.698474

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0412173ff62"
down_revision: Union[str, Sequence[str], None] = "2c120e249b8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attendance",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PRESENT",
                "PAID_LEAVE",
                "UNPAID_LEAVE",
                "HALF_DAY",
                name="attendance_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("overtime_hours", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "business_id",
            "employee_id",
            "date",
            name="uq_attendance_business_employee_date",
        ),
    )
    op.create_index(
        "ix_attendance_business_date",
        "attendance",
        ["business_id", "date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_attendance_business_date", table_name="attendance")
    op.drop_table("attendance")
    # ### end Alembic commands ###
