"""add salary basis columns in business and employees table

Revision ID: 3002c75f04c9
Revises: f0412173ff62
Create Date: 2026-06-23 14:27:45.044797

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3002c75f04c9"
down_revision: Union[str, Sequence[str], None] = "f0412173ff62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "businesses",
        sa.Column(
            "default_salary_basis",
            sa.Enum(
                "CALENDAR_DAYS",
                "FIXED_30_DAYS",
                "WORKING_26_DAYS",
                name="salary_basis",
                native_enum=False,
            ),
            server_default="working_26_days",
            nullable=False,
        ),
    )
    op.add_column(
        "employees",
        sa.Column(
            "salary_basis",
            sa.Enum(
                "CALENDAR_DAYS",
                "FIXED_30_DAYS",
                "WORKING_26_DAYS",
                name="salary_basis",
                native_enum=False,
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "salary_basis")
    op.drop_column("businesses", "default_salary_basis")
    # ### end Alembic commands ###
