"""add payroll tables

Revision ID: fb171256f079
Revises: 3002c75f04c9
Create Date: 2026-06-23 16:01:52.495908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb171256f079'
down_revision: Union[str, Sequence[str], None] = '3002c75f04c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_incomplete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_runs_business_id'), 'payroll_runs', ['business_id'], unique=False)
    op.create_table('payroll_line_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payroll_run_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('wage_type', sa.String(length=20), nullable=False),
    sa.Column('wage_rate', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('working_hours_per_day', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('overtime_multiplier', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('salary_basis', sa.String(length=30), nullable=False),
    sa.Column('basis_days', sa.Integer(), nullable=False),
    sa.Column('total_days_in_period', sa.Integer(), nullable=False),
    sa.Column('paid_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('lop_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('weekly_off_days', sa.Integer(), nullable=False),
    sa.Column('holiday_days', sa.Integer(), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('per_day_rate', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('per_hour_rate', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('base_pay', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('overtime_pay', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_pay', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_line_items_payroll_run_id'), 'payroll_line_items', ['payroll_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_line_items_payroll_run_id'), table_name='payroll_line_items')
    op.drop_table('payroll_line_items')
    op.drop_index(op.f('ix_payroll_runs_business_id'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    # ### end Alembic commands ###
